#pragma once

#define INVALID_SESSION_ID 0
#define IP_SIZE 16

#define IO_COUNT_RELEASE_VALUE 0x100000
#define ONE_SEND_WSABUF_MAX	50
#define MAX_RIO_RESULT 256

#define MAX_CLIENT_SEND_SIZE 4096

using SessionId = UINT64;
